stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t siz_image .
  only:
    - main

test-job:
  stage: test
  script:
    - docker run --rm -d siz_image
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - docker compose up -d
  only:
    - main
