services:
  db:
    image: postgres:15
    container_name: siz_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: siz_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: franwash_siz
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # redis:

  #   image: redis:7
  #   container_name: roof_redis

  siz_app:
    image: siz_image
    build:
      context: .
    env_file:
      - .env
    container_name: siz_app
    depends_on:
      # redis:
      #   condition: service_started
      db:
        condition: service_started
      # grafana:
      #   condition: service_started
      # prometheus:
      #   condition: service_started
    command: ["/auto_app/docker/app.sh"]
    ports:
      - 8000:8000

  # prometheus:
  #   image: prom/prometheus:v2.43.0
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   restart: unless-stopped
  #   ports:
  #     - 9090:9090

  # grafana:
  #   image: grafana/grafana:9.4.7
  #   container_name: grafana
  #   volumes:
  #     - grafanadata:/var/lib/grafana
  #   # depends_on:
  #   #   - prometheus
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000

volumes:
  postgresdata:
  # grafanadata:
  # prometheusdata:
